### PR TITLE
release workflow

### PR DESCRIPTION
**Pull request by djdanielsson**

### CODE REVIEW

**Review by sean-m-sullivan — APPROVED** [review]
Lgtm

**Review by swapdisk — CHANGES_REQUESTED** [review]
Let's add a CHANGELOG file to meet OpenSSF release notes requirements[1] and we'll use semantic version numbering[2].

[1] [https://bestpractices.coreinfrastructure.org/en/criteria/0#0.version_unique]
[2] [https://semver.org/spec/v2.0.0.html]

**Comment by swapdisk** [comment]
Ok, I made a v0.1.0-beta tag and pre-release. Now I'm looking at antsibull-changelog for release notes requirements.

**Comment by swapdisk** [comment]
So I think mostly I understand how this works now. :joy:

@djdanielsson, just need to set the title in `changelogs/config.yaml` to "Ansible Leapp Collection" and should be good to merge...

**Review by swapdisk — APPROVED** [review]

**Pull request merged**
